= Архитектурное решение "TeamBridge - Корпоративный мессенджер с групповыми чатами"

TeamBridge - корпоративный сервис для обмена мгновенными сообщениями с открытым исходным кодом, с возможностью обмена файлами, поиска и различных интеграций-плагинов с целью расширения функционала. Сервис используется в качестве внутреннего чата в организациях и компаниях, как альтернатива проприетарным аналогам: Slack, TeamCity, VKTeams. Важные преимущества TeamBridge 
- предполагает on-premise установку на собственных серверах компании с целью безопасности
- открытый код делает работу сервиса прозрачным и позволяет тонкую настройку и усовершенствования самой компанией
- Основной код предоставляет минимум функций по обмену мгновенных сообщений и файлов и расширяем за счет внешних интеграций и плагинов с целью увеличения функционала.

:doctype: book
:toc-title: Содержание
:chapter-signifier: Глава
:toc: left
:toclevels: 3
:icons: font
:imagesdir: ./doc/images
:sectnums:
:sectnumlevels: 3

== Требования

include::./doc/1.01. Функциональные требования.adoc[]

include::./doc/1.02. Нефункциональные требования.adoc[]

== Концептуальная архитектура

include::./doc/2.01 Схема концептуальной архитектуры.adoc[]

include::./doc/2.02 Описание концептуальной архитектуры.adoc[]

include::./doc/2.03 Пользователи решения.adoc[]

include::./doc/2.04 Внешние интеграции.adoc[]

include::./doc/2.05 Потоки данных и высокоуровневое взаимодействие.adoc[]

include::./doc/2.06 Модель данных.adoc[]
