=== Описание концептуальной архитектуры

С целью предоставления возможности дальнейшего расширения системы и последующего горизонтального масштабирования отдельных функций был выбран архитектурный стиль - микросервисы.
При этом был выбран Event Sourcing подход для параллельной обработки сообщений самим Chat Service, сервисом индексации сообщений и возможности чтения будущими сервисами.


Компоненты архитектуры

* API Gateway - входная точка REST API, где осуществляется аутентификация всех HTTP запросов, балансировка и ограничение трафика
* WebSocket Gateway - отдельный сервис для realtime соединений с клиентами (WebSocket), маршрутизации событий, контроля rate limit и статуса подключений
* Chat Service - основной бэкенд сервис для большинства операций обмена сообщениями, а также администрирования пользователей системы
* Search Service - сервис индексации/поиска пользователей и сообщений
* File Service - сервис, обеспечивающий загрузку файлов, прикрепленных к сообщению

* Keycloak + LDAP/AD - IAM сервис и корпоративный каталог пользователей

Взаимодействие API Gateway и WebSocket Gateway::
 * API Gateway обслуживает синхронные REST операции (поиск, CRUD, администрирование, загрузка файлов)
 * WebSocket Gateway обслуживает long lived соединения, подписки на события и доставку сообщений в реальном времени
 * WebSocket Gateway валидирует JWT токены через Keycloak (JWKS) и использует KeyDB для хранения session/presence с TTL
 * Chat Service публикует доменные события в Kafka, после чего WebSocket Gateway доставляет события онлайн пользователям

Хранилища::
 * S3 (minIO) - файловое хранилище
 * PostgreSQL database - база данных сообщений, чатов, профилей пользователей
 * KeyDB - кэш присутствия, статуса, профиля пользователя и WS сессий
 * Message Broker Kafka - журнал сообщений и изменений профилей пользователей