@startuml

hide empty members

skinparam component {
    BackgroundColor<<service>> LightBlue
    BorderColor<<service>> DarkBlue
    ArrowColor<<service>> DarkBlue
}

skinparam rectangle {
    BackgroundColor<<entity>> LightGreen
    BorderColor<<entity>> DarkGreen
    ArrowColor<<entity>> DarkGreen
}

    [UserProfile] <<entity>>
    [Chat] <<entity>>
    [Message] <<entity>>
    [UserNotifications] <<entity>>
    [FileRef] <<entity>>
    [ChatMember] <<entity>>
    [AuditLog] <<entity>>


UserProfile --> Message : отправляет
Message --> Chat : принадлежит
Chat --> ChatMember : участники
ChatMember --> UserProfile : пользователь
Message --> FileRef : ссылается на
Message --> UserNotifications: содержит
UserNotifications --> UserProfile: ссылается
Chat --> Message : последние сообщения
UserProfile --> AuditLog : админ-действие
AuditLog --> UserProfile : исполнитель
AuditLog --> Chat : target chat
AuditLog --> Message : target message


note left of [UserProfile]
  Профиль пользователя
  из Keycloak
  Только статус присутствия
  может изменяться
end note

note left of [Message]
  Сообщения с разными
  типами содержимого
  Редактируемые
end note

note left of [Chat]
  Личные и групповые
  чаты
  Групповые имеют админов
end note

note left of [FileRef]
  Прикрепленные файлы
  к сообщениям
end note

note left of [AuditLog]
  Лог действий администратора:
  блокировка пользователя,
  удаление участника,
  удаление сообщения/чата
end note


@enduml